// Generated by CoffeeScript 1.3.3
var Clock;

Clock = (function() {

  Clock.prototype.weekArray = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

  function Clock() {
    this.now = new Date;
    this.setTime("#time");
    this.setDate("#date");
    this.reload();
  }

  Clock.prototype.setDate = function(dom) {
    this.year = this.now.getFullYear();
    this.month = this.now.getMonth() + 1;
    this.day = this.now.getDate();
    this.week = this.weekArray[this.now.getDay()];
    return $(dom).html("" + this.year + "/" + this.month + "/" + this.day + "(" + this.week + ")");
  };

  Clock.prototype.setTime = function(dom) {
    this.hour = this.now.getHours();
    if (this.hour < 10) {
      this.hour = "0" + this.hour;
    }
    this.min = this.now.getMinutes();
    if (this.min < 10) {
      this.min = "0" + this.min;
    }
    this.sec = this.now.getSeconds();
    if (this.sec < 10) {
      this.sec = "0" + this.sec;
    }
    return $(dom).html("" + this.hour + ":" + this.min + ":" + this.sec);
  };

  Clock.prototype.reload = function() {
    return setTimeout("new Clock", 1000);
  };

  return Clock;

})();

new Clock;
