// Generated by CoffeeScript 1.3.3

require(['lib/canvas'], function() {
  console.log("lib/canvas ready.");
  return require(['canvas_test'], function() {
    console.log("canvas_test ready.");
    return null;
  });
});
