// Generated by CoffeeScript 1.3.3
var SelectGallery;

SelectGallery = (function() {

  function SelectGallery(main_dom, list_dom) {
    this.main_dom = main_dom;
    this.list_dom = list_dom;
    this.select();
  }

  SelectGallery.prototype.select = function() {
    var list_dom, main_dom;
    main_dom = this.main_dom;
    list_dom = this.list_dom;
    return $(list_dom).click(function() {
      var idx;
      idx = $(list_dom).index(this);
      $(main_dom).attr("src", this.src);
      $(list_dom).removeClass("select");
      return $(this).addClass("select");
    });
  };

  return SelectGallery;

})();

$(function() {
  var selectgallery;
  return selectgallery = new SelectGallery("#main", ".thumb");
});
