// Generated by CoffeeScript 1.3.3
var Audio, Gallery, Mixin, SelectGallery, SlideGallery,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Mixin = (function() {

  function Mixin() {}

  Mixin.prototype.augment = function(t) {
    var m, n, _results;
    _results = [];
    for (n in this) {
      m = this[n];
      _results.push(!(n === 'augment' || !(this[n].prototype != null)) ? t[n] = m : void 0);
    }
    return _results;
  };

  return Mixin;

})();

Audio = (function(_super) {

  __extends(Audio, _super);

  function Audio() {
    return Audio.__super__.constructor.apply(this, arguments);
  }

  Audio.prototype.audio = function(audio) {
    if (audio !== null) {
      return document.getElementById(audio);
    } else {
      return null;
    }
  };

  Audio.prototype.change_volume = function(volume) {
    var _this = this;
    if (volume !== null) {
      return $(volume).change(function() {
        return _this.audio.volume = $(volume).val();
      });
    }
  };

  return Audio;

})(Mixin);

Gallery = (function() {

  function Gallery(main_dom, list_dom) {
    this.main_dom = main_dom;
    this.list_dom = list_dom;
  }

  return Gallery;

})();

SelectGallery = (function(_super) {

  __extends(SelectGallery, _super);

  function SelectGallery(main_dom, list_dom) {
    SelectGallery.__super__.constructor.apply(this, arguments);
    this.select();
  }

  SelectGallery.prototype.select = function() {
    var list_dom, main_dom;
    main_dom = this.main_dom;
    list_dom = this.list_dom;
    return $(list_dom).click(function() {
      var idx;
      idx = $(list_dom).index(this);
      $(main_dom).attr("src", this.src);
      $(list_dom).removeClass("select");
      return $(this).addClass("select");
    });
  };

  return SelectGallery;

})(Gallery);

SlideGallery = (function(_super) {

  __extends(SlideGallery, _super);

  function SlideGallery(main_dom, list_dom, audio, volume) {
    if (audio == null) {
      audio = null;
    }
    if (volume == null) {
      volume = null;
    }
    SlideGallery.__super__.constructor.apply(this, arguments);
    Audio.prototype.augment(this);
    this.timerId = 0;
    this.change_speed = 1000;
    this.current_image_idx = 0;
    this.change_image();
    this.audio = Audio.prototype.audio(audio);
    this.change_volume(volume);
  }

  SlideGallery.prototype.change_current_image_idx = function() {
    this.current_image_idx += 1;
    if ($(this.list_dom).length === this.current_image_idx) {
      return this.current_image_idx = 0;
    }
  };

  SlideGallery.prototype.change_image = function() {
    var select_img;
    select_img = $(this.list_dom)[this.current_image_idx];
    this.change_main_image(select_img);
    return this.change_list_image(select_img);
  };

  SlideGallery.prototype.change_main_image = function(select_img) {
    return $(this.main_dom).attr("src", select_img.src);
  };

  SlideGallery.prototype.change_list_image = function(select_img) {
    $(this.list_dom).removeClass("select");
    return $(select_img).addClass("select");
  };

  SlideGallery.prototype.start = function() {
    var _this = this;
    this.change_image();
    if (this.timerId === 0) {
      return this.timerId = setInterval(function() {
        _this.change_current_image_idx();
        return _this.change_image();
      }, this.change_speed);
    }
  };

  SlideGallery.prototype.pause = function() {
    clearInterval(this.timerId);
    return this.timerId = 0;
  };

  SlideGallery.prototype.stop = function() {
    this.current_image_idx = 0;
    this.change_image();
    clearInterval(this.timerId);
    return this.timerId = 0;
  };

  SlideGallery.prototype.click_event = function(start, pause, stop) {
    var _this = this;
    $(start).click(function() {
      _this.start();
      if (_this.audio !== null) {
        return _this.audio.play();
      }
    });
    $(pause).click(function() {
      _this.pause();
      if (_this.audio !== null) {
        return _this.audio.pause();
      }
    });
    return $(stop).click(function() {
      _this.stop();
      if (_this.audio !== null) {
        return _this.audio.load();
      }
    });
  };

  return SlideGallery;

})(Gallery);

$(function() {
  var slide_gallery;
  new SelectGallery("#main", ".thumb");
  slide_gallery = new SlideGallery("#main", ".thumb", 'audio', '#volume');
  return slide_gallery.click_event('#button_start', '#button_pause', '#button_stop');
});
