// Generated by CoffeeScript 1.3.3
var SelectGallery;

SelectGallery = (function() {

  function SelectGallery(imgArray) {
    this.imgArray = imgArray;
    this.mainDom = null;
    this.listDom = null;
  }

  SelectGallery.prototype.select = function() {
    var imgArray, listDom, mainDom;
    imgArray = this.imgArray;
    mainDom = this.mainDom;
    listDom = this.listDom;
    return $(listDom).click(function() {
      var idx;
      idx = $(listDom).index(this);
      $(mainDom).attr("src", imgArray[idx]);
      $(listDom).removeClass("select");
      return $(this).addClass("select");
    });
  };

  SelectGallery.prototype.start = function() {
    return this.select();
  };

  return SelectGallery;

})();

$(function() {
  var imgArray, selectgallery;
  imgArray = ["img/sample0.jpg", "img/sample1.jpg", "img/sample2.jpg", "img/sample3.jpg", "img/sample4.jpg"];
  selectgallery = new SelectGallery(imgArray);
  selectgallery.mainDom = "#main";
  selectgallery.listDom = ".thumb";
  return selectgallery.start();
});
