// Generated by CoffeeScript 1.3.3
var drawCircle, drawLine, drawRect;

drawRect = function() {
  var canvas, context;
  canvas = document.getElementById("main");
  context = canvas.getContext("2d");
  context.strokeStyle = "red";
  context.strokeRect(50, 50, 100, 180);
  context.fillStyle = "blue";
  return context.fillRect(200, 50, 100, 180);
};

drawLine = function() {
  var canvas, context;
  canvas = document.getElementById("main");
  context = canvas.getContext("2d");
  context.strokeStyle = "#f00";
  context.beginPath();
  context.moveTo(350, 50);
  context.lineTo(600, 150);
  context.lineTo(400, 200);
  context.closePath();
  return context.stroke();
};

drawCircle = function() {
  var canvas, context;
  canvas = document.getElementById("main");
  context = canvas.getContext("2d");
  context.strokeStyle = "red";
  context.beginPath();
  context.arc(200, 350, 80, 0, 2 * Math.PI, false);
  context.stroke();
  context.fillStyle = "#00f";
  context.beginPath();
  context.moveTo(450, 350);
  context.arc(450, 350, 80, 0, 2 * Math.PI * (120 / 360), false);
  return context.fill();
};

$(function() {
  $('#draw_rect').click(function() {
    return drawRect();
  });
  $('#draw_line').click(function() {
    return drawLine();
  });
  return $('#draw_circle').click(function() {
    return drawCircle();
  });
});
