// Generated by CoffeeScript 1.3.3
var Drawer, drawCircle, drawLine, drawRect;

Drawer = (function() {

  function Drawer(canvas_id, line_color, fill_color) {
    var canvas;
    if (line_color == null) {
      line_color = "#333";
    }
    if (fill_color == null) {
      fill_color = "#fff";
    }
    canvas = document.getElementById(canvas_id);
    this.context = canvas.getContext("2d");
    this.lineColor(line_color);
    this.fillColor(fill_color);
  }

  Drawer.prototype.lineColor = function(color) {
    return this.context.strokeStyle = color;
  };

  Drawer.prototype.fillColor = function(color) {
    return this.context.fillStyle = color;
  };

  return Drawer;

})();

drawRect = function() {
  var drawer1, drawer2;
  drawer1 = new Drawer('main', '#f00');
  drawer1.context.strokeRect(50, 50, 100, 180);
  drawer2 = new Drawer('main', '#00f', '#00f');
  return drawer2.context.fillRect(200, 50, 100, 180);
};

drawLine = function() {
  var drawer;
  drawer = new Drawer('main', '#880');
  drawer.context.beginPath();
  drawer.context.moveTo(350, 50);
  drawer.context.lineTo(600, 150);
  drawer.context.lineTo(400, 200);
  drawer.context.closePath();
  return drawer.context.stroke();
};

drawCircle = function() {
  var drawer1, drawer2;
  drawer1 = new Drawer('main', '#088');
  drawer1.context.beginPath();
  drawer1.context.arc(200, 350, 80, 0, 2 * Math.PI, false);
  drawer1.context.stroke();
  drawer2 = new Drawer('main', '#000', '#00f');
  drawer2.context.beginPath();
  drawer2.context.moveTo(450, 350);
  drawer2.context.arc(450, 350, 80, 0, 2 * Math.PI * (120 / 360), false);
  return drawer2.context.fill();
};

$(function() {
  $('#draw_rect').click(function() {
    return drawRect();
  });
  $('#draw_line').click(function() {
    return drawLine();
  });
  return $('#draw_circle').click(function() {
    return drawCircle();
  });
});
