// Generated by CoffeeScript 1.3.3
var getSliderValue, value;

value = 0;

getSliderValue = function() {
  return value = $("#slider").val();
};

$(function() {
  return $("#create").click(function() {
    getSliderValue();
    return alert("slider value is " + value);
  });
});
